### ISSUE TITLE
getAddresses is send replying only Used Ips

### ISSUE THREAD

**Issue by needsone** [kompetenzbolzen/python-phpipam#2]
I am doing a huge mapping of our networks, I need all the Ips of my some vlan in my script.
But I need to do a list with used / unused Ips.
The example  in the example folder does not work.

**Comment by kompetenzbolzen** [comment]
python-phpipam is only a lightweight wrapper for the phpIPAM API. This is how phpIPAM works internally, afaik. It only stores used adresses. If you want to create a list of unused addresses, you would have to do that yourself.

This may help: https://stackoverflow.com/a/53648372

**Comment by needsone** [comment]
What I will do is to set the list of ip and test them with : 
/api/my_app/subnets/{id}/addresses/{ip}/
It should return the full vars and the tag should be include.
